package tictac7x.charges;

public enum ChargesItem {
    ARCLIGHT,
    ASH_SANCTIFIER,
    BARROWS_GEAR,
    BONE_CRUSHER,
    BOTTOMLESS_COMPOST_BUCKET,
    BRACELET_OF_SLAUGHTER,
    BRYOPHYTAS_STAFF,
    CELESTIAL_RING,
    CHRONICLE,
    CRYSTAL_SHIELD,
    EXPEDITIOUS_BRACELET,
    FALADOR_SHIELD,
    GRICOLLERS_CAN,
    IBANS_STAFF,
    PHARAOHS_SCEPTRE,
    SKULL_SCEPTRE,
    SLAYER_RING,
    SOUL_BEARER,
    TRIDENT_OF_THE_SEAS,
    XERICS_TALISMAN,
}
